select * from dog where cat <> 4;
select legs, hairy from dog;
select max(length) from dog;
SELECT COUNT(DISTINCT country) FROM publishers;
select one, two from hairy where two <> 4 and one = 2;
select one, two from hairy where two <> 4 and one = 2 order by two;
select one, two from hairy where two <> 4 and one = 2 limit 4 order by two ascending, dog descending;
select foo.a from foo;
select a as b from foo;
select a from foo as bar;
SELECT * FROM PERSON WHERE SURNAME IS not NULL AND FIRSTNAME = 'Jason';
SELECT * FROM PERSON WHERE SURNAME IS NULL;
SELECT * FROM PERSON WHERE SURNAME = '' AND FIRSTNAME = 'Jason';
-- Test Comment;
# Test Comment;
