-- SQL PARSER TESTCASE
-- SQL_PARSER_FLAG_MYSQL
LOCK TABLES mytable READ, db.mytable AS mytab2 WRITE

-- SQL PARSER TESTCASE
-- SQL_PARSER_FLAG_MYSQL
UNLOCK TABLES

-- SQL PARSER TESTCASE
-- SQL_PARSER_FLAG_MYSQL
-- SQL_PARSER_FLAG_FAIL
UNLOCK TABLES mytable